### ISSUE TITLE
Spent time email reminder

### ISSUE THREAD

**Issue by jigmelam** [Hopebaytech/redmine_mail_reminder#34]
At first thank you so much for all your help.
Everyday automatically, I want to send email notifications to all people have spent time < 2 hours in yesterday.
Could you please show me how to do that ?

Thank you!

**Comment by Androc** [comment]
I may be wrong but I think it is not possible to send reminders about users.

It is only about issues.

You can send, for example a reminder about issues not modified since 3 days but you can't target users.

The possibilities are limited to the possibilities of the "saved issues queries" (the queries you can save when you make an issues filter).

**Comment by jigmelam** [comment]
This is a mail notification from my friend company's Redmine. I think they wrote their own script or plugin.
 
![screen shot 2015-06-01 at 3 43 44 pm](https://cloud.githubusercontent.com/assets/11434836/7960544/92ee1552-0a2b-11e5-9539-90ff0388413d.png)

**Comment by Androc** [comment]
Maybe it is an other plugin.

The Redmine_Mail_Reminder uses saved queries but maybe you have other plugins that tracks time spent by users.

**Comment by Androc** [comment]
Ask your friend if he can asks his administrator :)

**Comment by jcppkkk** [comment]
close it as it's not what redmine_mail_reminder can do currently
